/* eslint-disable @typescript-eslint/no-require-imports */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./*.js"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#51b2fe",
        "surface-container-low": "#f2f4f3",
        "inverse-on-surface": "#eff1f0",
        "on-primary-fixed-variant": "#005312",
        "outline": "#707a6c",
        "on-primary-container": "#cbffc2",
        "on-secondary-container": "#00436a",
        "surface": "#f8faf9",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#354a53",
        "outline-variant": "#bfcaba",
        "on-tertiary-fixed": "#071e27",
        "tertiary": "#445963",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#001d32",
        "secondary-fixed-dim": "#96ccff",
        "on-primary-fixed": "#002204",
        "surface-tint": "#1b6d24",
        "surface-variant": "#e1e3e2",
        "background": "#f8faf9",
        "tertiary-fixed": "#cfe6f2",
        "on-error": "#ffffff",
        "primary": "#0d631b",
        "surface-dim": "#d8dada",
        "error": "#ba1a1a",
        "surface-bright": "#f8faf9",
        "primary-container": "#2e7d32",
        "tertiary-fixed-dim": "#b4cad6",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#a3f69c",
        "secondary": "#00639a",
        "on-tertiary-container": "#e1f4ff",
        "surface-container": "#eceeed",
        "on-surface": "#191c1c",
        "secondary-fixed": "#cee5ff",
        "on-background": "#191c1c",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e1e3e2",
        "on-surface-variant": "#40493d",
        "surface-container-high": "#e6e9e8",
        "inverse-surface": "#2e3131",
        "tertiary-container": "#5c717b",
        "primary-fixed-dim": "#88d982",
        "inverse-primary": "#88d982",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#004a75"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
